export const text = {
  vi: {
    home: "Trang chủ",
    about: "Về tôi",
    services: "Dịch vụ",
    projects: "Dự án",
    contact: "Liên hệ",
    login: "Đăng nhập",
    register: "Đăng ký",
    call: "Gọi ngay",
    zalo: "Zalo Chat",
    messenger: "Messenger",
  },
  en: {
    home: "Home",
    about: "About",
    services: "Services",
    projects: "Projects",
    contact: "Contact",
    login: "Login",
    register: "Register",
    call: "Call Now",
    zalo: "Zalo Chat",
    messenger: "Messenger",
  },
};
